import { NgModule }     from '@angular/core';
import {	MatButtonModule,
					MatButtonToggleModule,	
					MatAutocompleteModule,
         	MatCheckboxModule,
					MatCardModule,
					MatChipsModule,
					MatDatepickerModule,
					MatDialogModule,
					MatGridListModule,
					MatIconModule,
					MatInputModule,
					MatListModule,
					MatNativeDateModule,
					MatMenuModule,
					MatProgressBarModule,
					MatProgressSpinnerModule,
					MatRadioModule,
					MatSelectModule,
					MatSliderModule,
					MatSlideToggleModule,
					MatSnackBarModule,
					MatTabsModule,
					MatExpansionModule
       } from '@angular/material';
  
import { MatToolbarModule } from '@angular/material/toolbar';

@NgModule({
	imports: [
		MatButtonModule,
		MatButtonToggleModule,
		MatAutocompleteModule,
   	MatCheckboxModule,
		MatCardModule,
		MatDatepickerModule,
		MatDialogModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatNativeDateModule,
		MatMenuModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatSelectModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatTabsModule,
		MatExpansionModule,
		MatToolbarModule,
	],
	exports:[
		MatButtonModule,
		MatButtonToggleModule,
		MatAutocompleteModule,
   	MatCheckboxModule,
		MatCardModule,
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatNativeDateModule,
		MatMenuModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatSelectModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatTabsModule,
		MatExpansionModule,
		MatToolbarModule,
	]
})
export class DevelarMaterialModule {}
